### ISSUE TITLE
英文引用折行问题

### ISSUE THREAD

**Issue by summershrimp** [hushidong/biblatex-gb7714-2015#11]
![图片](https://dn-coding-net-production-pp.qbox.me/4a63050d-6d0a-4dc0-b9dd-bd393e4c9e0a.png)

**Comment by summershrimp** [comment]
似乎是因为latex无法在[C]//Global这里将global和//分开 导致无法折行

**Comment by summershrimp** [comment]
```tex
\printtext{\allowbreak\texttt{//}\addnbthinspace\allowbreak}%%\texttt{//}
```

这样搞一下会好一点。供参考

**Comment by hushidong** [comment]
断行这个问题我之前是这样考虑的，因为//要体现的是前后的所属关系，所以我希望不在//前后直接断行，而希望在其前后的词后断行，但有时因为其后的词较长可能会超出，所以加个nbspace空格告诉latex后面的词可以断词，这样可以避免超出。 所以我的这种处理和你的建议的方式是一个选择问题，为避免超出是在//后断行，还是在其后的词中或词尾断行。 这个问题标准好像没有细说，如果需要的话当然可以按照你的建议方式处理。当然还有更简单的方式是把thinnbspace换成thinspace。 发自网易邮箱大师 在2017年05月26日 01:00，Yibai Zhang 写道： \printtext{\allowbreak\texttt{//}\addnbthinspace\allowbreak}%%\texttt{//} 这样搞一下会好一点。供参考 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by hushidong** [comment]
从你给的图看如果没有更好的让global这行断行的方式，你建议的方式是完全可以采用的。

**Comment by zepinglee** [comment]
我记得标准有个实例是在 // 后断行的，虽然标准的排版不算很标准，但我选择的是 //\allowbreak，

**Comment by hushidong** [comment]
嗯，这样也是不错的。

**Comment by hushidong** [comment]
这个问题最终的解决方案是在//后面加可断行小空格，以使换行更自由。

这个问题已经解决，没有新的情况先关闭啦。
