### ISSUE TITLE
conference reference problem 

### ISSUE THREAD

**Issue by hughhugh** [hushidong/biblatex-gb7714-2015#16]
Hi, I met some citing problem in inproceedings, which is as the following,
![image](https://user-images.githubusercontent.com/9352717/27835952-d36c091c-610f-11e7-8384-c9d6e073aa2e.png)

the exameple from google :
![image](https://user-images.githubusercontent.com/9352717/27836025-359c3d64-6110-11e7-81e5-4c9e68e92826.png)

So, how can I deal with that thing?  Thank you.

**Comment by hushidong** [comment]
Hello, If you do not want the dealing with publish items which is requested by GBT7714 that the missed publisher/address should be replaced by 出版者不详/出版地不详or sn/sl, you can set the option gupub=false, the added publish items will be removed. Enjoy! hzz 20170705 发自网易邮箱大师 在2017年07月04日 23:28，Wu Nailong 写道： Hi, I met some citing problem in inproceedings, which is as the following, the exameple from google : So, how can I deal with that thing? Thank you. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by WenboSheng** [comment]
pls list you bib source code. The publisher should be IEEE rather than s.n. I think there must be some items mismatched in your bib entry.

**Comment by hushidong** [comment]
关于隐藏出版社和出版者，已经有更好的处理方法。即使用gbpub=false。

这个问题已经解决，没有新的情况先关闭啦
