### ISSUE TITLE
MiKTeX v2.9 makefile.bat 编译报错

### ISSUE THREAD

**Issue by JackWzh** [hushidong/biblatex-gb7714-2015#17]
直接clone到本地，未做任何改动，运行批处理程序时报出了下面的错误：
`("C:\Program Files\MiKTeX 2.9\tex\latex\biblatex\biblatex.def")
(gb7714-2015.bbx

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1 ﻿
       %%
? `

**Comment by hushidong** [comment]
升级biblatex,他的版本太老了，在ctex2.9里 发自网易邮箱大师 在2017年08月02日 19:46，Old Jack 写道： 直接clone到本地，未做任何改动，运行批处理程序时报出了下面的错误： `("C:\Program Files\MiKTeX 2.9\tex\latex\biblatex\biblatex.def") (gb7714-2015.bbx ! LaTeX Error: Missing \begin{document}. See the LaTeX manual or LaTeX Companion for explanation. Type H for immediate help. ... l.1 ﻿ %% ? ` — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
