### ISSUE TITLE
请教一下关于宏包命名问题

### ISSUE THREAD

**Issue by zepinglee** [hushidong/biblatex-gb7714-2015#22]
我打算把我的 BibTeX style 发布到 CTAN，所以正在考虑宏包命名问题。

标准的正式名称是 《GB/T 7714-2015 ...》，为何你的宏包只有 gb7714 （丢掉 “/T”），请教一下你是怎么考虑的。

以及带个 “-2015” 的后缀是不是稍显啰嗦。

**Comment by hushidong** [comment]
是这样的，去掉T是为了方便书写，加上-2015是为了明确2015年的标准，且-符号不影响什么所以就加上了。 另外这个-本来想用下划线，但显然它在tex中有特殊的意义，所以就用了-。 关于/T，你可以试一下加上，如果有问题，ctan工作人员一般会建议怎么改的。 发自网易邮箱大师 在2017年12月13日 21:58，Zeping Lee 写道： 我打算把我的 BibTeX style 发布到 CTAN，所以正在考虑宏包命名问题。 标准的正式名称是 《GB/T 7714-2015 ...》，为何你的宏包只有 gb7714 （丢掉 “/T”），请教一下你是怎么考虑的。 以及带个 “-2015” 的后缀是不是稍显啰嗦。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by zepinglee** [comment]
好的，感谢！那我顺便再请教一个问题吧。

我看到你的文档里提到了“利用 perl 进行动态数据修改”，但我目前对 biblatex 不太了解，这个似乎是直接处理 bib 文件的内容？

我想请教一下有没有可能利用 TEXBIN 里的工具对 bib 文件进行操作：提取出每条 entry 的作者姓名（假定中文的）的拼音，然后再写入一条 `authorpinyin = {ma3 ke4 si1}` 的域？这样我就可以利用 BibTeX 自动排序了。

**Comment by zepinglee** [comment]
嗯感谢！我应该能实现这个，刚刚看到 texlive 还有个 bibtexperllib 的工具，好像简化了不少工作。
