### ISSUE TITLE
需要怎样安装bbx文件呢？

### ISSUE THREAD

**Issue by liubenyuan** [hushidong/biblatex-gb7714-2015#23]
我采用的是最小例子，然后将项目中所有`.bbx`和`.cbx`都放在当前目录下，编译时提示我找不到`gb7714-2015`。使用的biblatex是3.9版本，其余所有包都更新到了texlive最新版。

PS：我看在bbx文件中，没有检测3.9，跟这个有关么？我觉得其实可以不向后兼容，只要保持最新的特性即可。biblatex稳定后再考虑处理的问题。

可复现的最小例子是：

**（2018/1/1：移除了冒号，注意`gb7714-2015`之间要用英文的符号）**

```latex
\documentclass{article}%文档类
\RequirePackage[CJKchecksingle,no-math]{xeCJK}
%%%% Windows Thesis Fonts
\setmainfont{Times New Roman PS Std}
\setsansfont{Arial}
\setmonofont{Courier New}
%%%% Using Founder Family Fonts
\setCJKmainfont[BoldFont={FZYaSong-DB-GBK}]{FZShuSong_GB18030-Z01}
\setCJKsansfont{FZHei-B01} % Hei
\setCJKmonofont{FZFangSong-Z02} % fs
%%%% alias
\setCJKfamilyfont{song}{FZShuSong_GB18030-Z01}
\setCJKfamilyfont{hei}{FZHei-B01}
\setCJKfamilyfont{fs}{FZFangSong-Z02} % fang-song
\setCJKfamilyfont{kai}{FZKai-Z03} % Kai

%加载hyperref宏包，使用超链接
\usepackage[colorlinks=true,pdfstartview=FitH,linkcolor=blue,anchorcolor=violet,citecolor=magenta]{hyperref}

%加载biblatex宏包，使用参考文献
%其中后端backend使用biber
%引用样式citestyle，著录样式bibstyle都采用gb7714−2015样式
\usepackage[backend=biber, bibstyle=gb7714-2015,%nature,%
citestyle=gb7714-2015%,backref=true%
]{biblatex}
%biblatex宏包的参考文献数据源加载方式
\addbibresource[location=local]{example.bib}

%正文区开始:
\begin{document}
%正文内容，引用参考文献
详见文献\cite{Peebles2001−100−100}\parencite{Miroslav2004−−}
参考文献\cite[见][49页]{蔡敏2006−−}\parencite[见][49页]{Miroslav2004−−}

%打印参考文献表
\printbibliography[heading=bibliography,title=参考文献]
\end{document}
```

**Comment by hushidong** [comment]
gb7714-2015外面没有引号的，去掉试试 hzz 20171229 发自网易邮箱大师 在2017年12月29日 22:25，liubenyuan 写道： 我采用的是最小例子，然后将项目中所有.bbx和.cbx都放在当前目录下，编译时提示我找不到gb7714-2015。使用的biblatex是3.9版本，其余所有包都更新到了texlive最新版。 可复现的最小例子是： \documentclass{article}%文档类
\RequirePackage[CJKchecksingle,no-math]{xeCJK}
%%%% Windows Thesis Fonts
\setmainfont{Times New Roman PS Std}
\setsansfont{Arial}
\setmonofont{Courier New}
%%%% Using Founder Family Fonts
\setCJKmainfont[BoldFont={FZYaSong-DB-GBK}]{FZShuSong_GB18030-Z01}
\setCJKsansfont{FZHei-B01} % Hei
\setCJKmonofont{FZFangSong-Z02} % fs
%%%% alias
\setCJKfamilyfont{song}{FZShuSong_GB18030-Z01}
\setCJKfamilyfont{hei}{FZHei-B01}
\setCJKfamilyfont{fs}{FZFangSong-Z02} % fang-song
\setCJKfamilyfont{kai}{FZKai-Z03} % Kai

%加载hyperref宏包，使用超链接
\usepackage[colorlinks=true,pdfstartview=FitH,linkcolor=blue,anchorcolor=violet,citecolor=magenta]{hyperref}

%加载biblatex宏包，使用参考文献
%其中后端backend使用biber
%引用样式citestyle，著录样式bibstyle都采用gb7714−2015样式
\usepackage[backend=biber, bibstyle="gb7714−2015",%nature,%
citestyle="gb7714−2015"%,backref=true%
]{biblatex}
%biblatex宏包的参考文献数据源加载方式
\addbibresource[location=local]{example.bib}

%正文区开始:
\begin{document}
%正文内容，引用参考文献
详见文献\cite{Peebles2001−100−100}\parencite{Miroslav2004−−}
参考文献\cite[见][49页]{蔡敏2006−−}\parencite[见][49页]{Miroslav2004−−}

%打印参考文献表
\printbibliography[heading=bibliography,title=参考文献]
\end{document} — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by liubenyuan** [comment]
还是不行。

**Comment by hushidong** [comment]
下来以后，你随便编译一个eg开头的例子都可以啊。然后再比较一下，就能找到原因了，再试试 发自网易邮箱大师 在2017年12月30日 11:47，liubenyuan 写道： 还是不行。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by hushidong** [comment]
\usepackage[backend=biber, bibstyle="gb7714−2015",%nature,% citestyle="gb7714−2015"%,backref=true% ]{biblatex} 改为 \usepackage[backend=biber, bibstyle=gb7714−2015,%nature,% citestyle=gb7714−2015%,backref=true% ]{biblatex} 发自网易邮箱大师 在2017年12月30日 11:47，liubenyuan 写道： 还是不行。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by hushidong** [comment]
是因为gb7714-2015中间的这个短横线是英文的-，你直接在pdf中复制的是－，所以会找不到。两者是不同的，复制的时候最好复制源代码中的内容。而不是pdf中的，因为listings环境把-改了。

**Comment by hushidong** [comment]
我把listing环境中的字体改了，以后pdf中的也是原来的-了，可以复制了。

**Comment by liubenyuan** [comment]
谢谢你！我的粗心大意。现在是能找到bbx文件了，但是在windows下biber编译时编码自动退回到cp936了，导致找不到Key。

```bash
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LC_ALL = "en_US.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the system default locale ("Chinese (Simplified)_China.936").
INFO - This is Biber 2.9
INFO - Logfile is 'test.blg'
INFO - Reading 'test.bcf'
INFO - Found 3 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'example.bib' for section 0
INFO - LaTeX decoding ...
INFO - Found BibTeX data source 'example.bib'
WARN - I didn't find a database entry for 'Peebles2001−100−100' (section 0)
WARN - I didn't find a database entry for 'Miroslav2004−−' (section 0)
WARN - I didn't find a database entry for '蔡敏2006−−' (section 0)
INFO - Overriding locale 'en-US' defaults 'normalization = NFD' with 'normalization = prenormalized'
INFO - Overriding locale 'en-US' defaults 'variable = shifted' with 'variable = non-ignorable'
INFO - Sorting list 'none/global//global/global' of type 'entry' with template 'none' and locale 'en-US'
INFO - No sort tailoring available for locale 'en-US'
INFO - Writing 'test.bbl' with encoding 'UTF-8'
INFO - Output to test.bbl
INFO - WARNINGS: 3
```

**Comment by hushidong** [comment]
把bib文件的编码改回utf-8试试？ 发自网易邮箱大师 在2018年01月01日 18:47，liubenyuan 写道： 谢谢你！我的粗心大意。现在是能找到bbx文件了，但是在windows下biber编译时编码自动退回到cp936了，导致找不到Key。 perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LC_ALL = "en_US.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the system default locale ("Chinese (Simplified)_China.936").
INFO - This is Biber 2.9
INFO - Logfile is 'test.blg'
INFO - Reading 'test.bcf'
INFO - Found 3 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'example.bib' for section 0
INFO - LaTeX decoding ...
INFO - Found BibTeX data source 'example.bib'
WARN - I didn't find a database entry for 'Peebles2001−100−100' (section 0)
WARN - I didn't find a database entry for 'Miroslav2004−−' (section 0)
WARN - I didn't find a database entry for '蔡敏2006−−' (section 0)
INFO - Overriding locale 'en-US' defaults 'normalization = NFD' with 'normalization = prenormalized'
INFO - Overriding locale 'en-US' defaults 'variable = shifted' with 'variable = non-ignorable'
INFO - Sorting list 'none/global//global/global' of type 'entry' with template 'none' and locale 'en-US'
INFO - No sort tailoring available for locale 'en-US'
INFO - Writing 'test.bbl' with encoding 'UTF-8'
INFO - Output to test.bbl
INFO - WARNINGS: 3 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by liubenyuan** [comment]
问题解决啦！bib文件是utf8编码的，问题还是在于正文中`-`复制粘帖时，写成中文的了。改成英文的就编译通过了！谢谢啦～
