### ISSUE TITLE
biblatex无法处理example.bib条目中的Latex命令，例如\LaTeX{}

### ISSUE THREAD

**Issue by liubenyuan** [hushidong/biblatex-gb7714-2015#24]
当bib文件中存在latex命令时，例如\LaTeX{}时，biblatex编译出错。文件跟 #23 中一样。但是如果把bib中的`\LaTeX{}`变为`\TeX{}`编译就没问题。

```bibtex
@Book{Peebles2001-100-100,
  Title                    = {Probability, random variable, and random signal Principles, and \LaTeX{}},
  Address                  = {New York},
  Author                   = {von Peebles, Jr., P. Z.},
  Edition                  = {4},
  Pages                    = {100},
  Publisher                = {McGraw-Hill},
  Year                     = {2001}
}
```

编译错误为：

```bash
(./test.bbl))
! Incomplete \iffalse; all text was ignored after line 37.
<inserted text> 
                \fi 
<*> test.tex
            
! Emergency stop.
<*> test.tex
```

**Comment by hushidong** [comment]
这个问题找着了，是我写的cjk判断函数遇到\latex这个命令出问题，我想想怎么解决 发自网易邮箱大师 在2018年01月02日 10:15，liubenyuan 写道： 当bib文件中存在latex命令时，例如\LaTeX{}时，biblatex编译出错。文件跟 #23 中一样。但是如果把bib中的\LaTeX{}变为\TeX{}编译就没问题。 @Book{Peebles2001-100-100,
  Title                    = {Probability, random variable, and random signal Principles, and \LaTeX{}},
  Address                  = {New York},
  Author                   = {von Peebles, Jr., P. Z.},
  Edition                  = {4},
  Pages                    = {100},
  Publisher                = {McGraw-Hill},
  Year                     = {2001}
}
 编译错误为： (./test.bbl))
! Incomplete \iffalse; all text was ignored after line 37.
<inserted text> 
                \fi 
<*> test.tex
            
! Emergency stop.
<*> test.tex — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by hushidong** [comment]
这个问题是这样的，
因为在cjk判断函数中，使用了xtring的subchar函数StrChar函数来抽取字符，但这个函数默认情况下需要其参数完全展开。因为\LaTeX{}宏比较复杂，展开时会出现问题。设置该函数不展开或展开一次，都可以解决判断出错的问题。比如:

    \expandarg
    %
    \StrChar{english}{1}[\tempa]%
    \tempa

    \StrChar{中文}{1}[\tempa]%
    \tempa

    \StrChar{english \LaTeX{} abc}{1}[\tempa]%
    \tempa

但解决的是直接给出文本的情况，在biblatex使用中需要用\thefield取出文本，显然\thefield不知展开一次，因此不展开或者展开一次，都会出现问题，所以无解。只能从另外一个角度出发。

考虑到动态数据修改时，也可以利用正则表达式抽取数据，因此

**Comment by liubenyuan** [comment]
好的！大牛你太厉害了~~
