### ISSUE TITLE
建议：项目的目录组织

### ISSUE THREAD

**Issue by liubenyuan** [hushidong/biblatex-gb7714-2015#25]
有关项目的目录组织有一些建议：

  1. git中最好不添加pdf文件。pdf是二进制文件，会增加`.git`目录的大小。这样会导致`git clone`一次时间过长，而且不利于维护。
  2. 样例的pdf文件可以针对每一个例子，截一个标准截图（分辨率不用太高），放在`images/`目录下，这样在`Readme.md`中就可以添加了，一个一个放上去很直观也很有吸引力。
  3. `Readme.md`中可以写一个简短的安装、测试教程（一节）。比如用你目录中的最小的例子，然后编译的命令（`makefile`或者`make.bat`），最终效果的截图。这样更有利于上手的。
  4. 我对底层不太了解，具体`xelatex`的编译命令应该是`--synctex=-1`还是`-synctex=1`呢？实际中，我都是用的`-synctex=1`。
  5. 目录结构可以是`src/`，`examples/`，`images/`，`Readme.md`，`License.txt`之类的。这样也有利于维护代码。唯一的缺点就是`.bbx`和`.cbx`文件编译时需要位于`example/`目录下，导致在`src/`和`examples/`下有两份存储。
  6. 要是能提交到默认的biblatex项目中（官方`bbx/`中，`cbx/`中）就更好啦！

**Comment by hushidong** [comment]
好好，这些建议很好，非常感谢！ 这个包已经提交到ctan上，texlive是的带的。因为考虑了不同版本biblatex的兼容性，提交给biblatex官方附带可能不太合适，官方附带的主要是标准样式。 发自网易邮箱大师 在2018年01月03日 09:41，liubenyuan 写道： 有关项目的目录组织有一些建议： git中最好不添加pdf文件。pdf是二进制文件，会增加.git目录的大小。这样会导致git clone一次时间过长，而且不利于维护。 样例的pdf文件可以针对每一个例子，截一个标准截图（分辨率不用太高），放在images/目录下，这样在Readme.md中就可以添加了，一个一个放上去很直观也很有吸引力。 Readme.md中可以写一个简短的安装、测试教程（一节）。比如用你目录中的最小的例子，然后编译的命令（makefile或者make.bat），最终效果的截图。这样更有利于上手的。 我对底层不太了解，具体xelatex的编译命令应该是--synctex=-1还是-synctex=1呢？实际中，我都是用的-synctex=1。 目录结构可以是src/，examples/，images/，Readme.md，License.txt之类的。这样也有利于维护代码。唯一的缺点就是.bbx和.cbx文件编译时需要位于example/目录下，导致在src/和examples/下有两份存储。 要是能提交到默认的biblatex项目中（官方bbx/中，cbx/中）就更好啦！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by hushidong** [comment]
1. 添加pdf的确是个问题，但考虑到提交ctan时的方便，就放着了。

2. readme中给出截图

3. readme给出了示例

4. --synctex=-1和-synctex=1，都没有问题，我用的是winedt，--synctex=-1是它的默认选项，所以就直接用了。

5. 还是考虑提交ctan的方便性，所以用的一层的目录结构。

**Comment by liubenyuan** [comment]
ok!

**Comment by hushidong** [comment]
准备按你建议的方式重新组织。下级目录中文件编译的问题可以利用脚本来解决，比如复制样式文件等。
