### ISSUE TITLE
请问如何将作者之间的分隔符由逗号调整为and？

### ISSUE THREAD

**Issue by lixiangnlp** [hushidong/biblatex-gb7714-2015#43]
请问如何将作者之间的分隔符由逗号调整为and？

**Comment by hushidong** [comment]
\DeclareDelimFormat[bib]{multinamedelim}{\addspace and \addspace} \DeclareDelimFormat[bib]{finalnamedelim}{\addspace and \addspace} 你用的biblatex版本比较新吧？在导言区加上述命令。版本较考，则重定义两个宏， \multinamedelim \finalnamedelim hzzmail 邮箱：hzzmail@sjtu.org 签名由 网易邮箱大师 定制 在2018年08月15日 11:18，Xiang Li 写道： 请问如何将作者之间的分隔符由逗号调整为and？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by hushidong** [comment]
不过，中文用and这种方式，不好看吧。
