### ISSUE TITLE
Biblatex (ver 3.11) doesn't load in xxxxx.tex file which emacs (ver 25.2.2) re-visite

### ISSUE THREAD

**Issue by xiaodongcentury** [hushidong/biblatex-gb7714-2015#44]
At first, Thanks for your biblatex-gb7714-2015 style.
My work enviroment is as follows: Debian GNU/Linux testing (buster), TeXLive 2018, biber (2.11), ctex (2.4.14).
The phenomenon is,
I create a xxxxx.tex file, and the documentclass is article. I include biblatex package, and the \addbibresource command is actived. After C-c and C-c, the tex file is well compiled, and the pdf file is ready with no error.
Once the tex file is closed and open again. C-c then C-c after the auxiliary files are removed, there is error "unresolved citation". Meanwhile the \addbibresource command doesn't usable, i.e. C-c then C-m, and input "add", then press TAB key, the minibuffer shows " No match". 
Only manual input usepackage "biblatex", then the command \addbibresource command is usable once again, and C-c then C-c will work with no error.
Is there anything auto re-load package "biblatex" without manual load it after re-open the tex file?
Thanks!

**Comment by hushidong** [comment]
is there a step `biber  jobname` between two C-c in your compiling command chain?

the general procedure to compile is
```
xelatex jobname.tex 	
biber jobname 	
xelatex jobname.tex 	
xelatex jobname.tex
```

no matter what editor you used, the step biber is necessary. I am not familer with emacs，but I think the problem may be caused by this step.

you can check your settings of emacs to set the right command biber to compile.

you can also use command `latexmk` instead of the above four commands.

**Comment by xiaodongcentury** [comment]
Thanks! I'll show you the screenshots:
![image](https://user-images.githubusercontent.com/20276890/45612001-1eeadf00-ba27-11e8-9e2f-055e6699a82f.png)
![image](https://user-images.githubusercontent.com/20276890/45612029-3b871700-ba27-11e8-94d4-965fdb38dac6.png)
Very well, there's no error!
Now I'll close the tex file and re-open, 
![image](https://user-images.githubusercontent.com/20276890/45614741-134fe600-ba30-11e8-9c86-8f8f4c765b32.png)
![image](https://user-images.githubusercontent.com/20276890/45614832-5f9b2600-ba30-11e8-8fae-f7ed21dface2.png)
![image](https://user-images.githubusercontent.com/20276890/45614866-7e012180-ba30-11e8-8397-88c7279aa114.png)
![image](https://user-images.githubusercontent.com/20276890/45614947-bb65af00-ba30-11e8-80ee-2e6fca9a8d07.png)
![image](https://user-images.githubusercontent.com/20276890/45615056-139cb100-ba31-11e8-83aa-8566632bcff1.png)
Please note the superscript [frey*]!
After i re-add biblatex package, then add bibresource, and compile the tex file,
![image](https://user-images.githubusercontent.com/20276890/45615352-dd136600-ba31-11e8-8fef-9498222c7444.png)
Please note the "%" symbol in tex file.
![image](https://user-images.githubusercontent.com/20276890/45615459-2a8fd300-ba32-11e8-844f-371c9bda451b.png)

**Comment by hushidong** [comment]
I will give you an explaination

the four step compiling process：
```
xelatex jobname.tex 	
biber jobname 	
xelatex jobname.tex 	
xelatex jobname.tex
```

the 1th step： biblatex will generate a bcf file, which conatains the citation info.
the 2th step :  biber will generate a bbl file, which contains the reference info of the citations
the 3th step :  biblatex will generate the bibliography list
the 4th step :  biblatex will generate the correct backref info.

so the superscript [frey*] means the biber was needed to run again.
and the lack of `引用页` meas the last step was needed.

so from the example you given , it can be infered that when you inserted a new cite to the tex file, the compiling tool of the emacs can not identify the change so that the compiling procedure was not executed completely, some steps were lost. 

so if want to get the right output, we should run all the steps everytime.

**Comment by xiaodongcentury** [comment]
Thanks, i'll try the terminal command other than emacs.
Yes, you're right. From the terminal command: xelatex, then biber, then xelatex, xelatex again, at last, i get the right PDF document. Your extrapolation maybe right. I don't know whether it's a bug of Emacs, or just my enviroment is not configured right.
Many thanks again.

**Comment by sd44** [comment]
>  I don't know whether it's a bug of Emacs, or just my enviroment is not configured right.
> Many thanks again.

这不是emacs的bug，而是你没有设置好…
如hushidong所说，你可在emacs aucTeX中设置TeX编译命令为latexmk，详情请google。

另外，预设一个 ~/.latexmkrc，作为latexmk的参数较好，只需要在.latexmkrc中设定一句话就可实现xelatex和biber的自动编译。

```
$pdf_mode = 5;
```

**Comment by xiaodongcentury** [comment]
非常感谢，是我的emacs配制有问题，Linux是区分大小写的，我当时没有注意到，后来在另外一台电脑上，重新配制emacs，编译时完全没有问题，我重新审查这台电脑emacs配制文件，才发现这个问题。
