### ISSUE TITLE
少了个“}”？

### ISSUE THREAD

**Issue by wayne508** [hushidong/biblatex-gb7714-2015#9]
TeX STOPPED: File ended while scanning use of \@argde{\testCJKfirst {\thefield {title}}\iflistundef {location}{\iffieldequalstr 
TeX reports the error was in file:0989 \RequireBibliographyStyle{\blx@bbxfile}

**Comment by hushidong** [comment]
你好， 在哪个位置，你的例子能给一个么？ hzz 20170512 发自网易邮箱大师 在2017年05月12日 10:38，wayne508 写道： TeX STOPPED: File ended while scanning use of @argde{\testCJKfirst {\thefield {title}}\iflistundef {location}{\iffieldequalstr TeX reports the error was in file:0989 \RequireBibliographyStyle{\blx@bbxfile} — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by wayne508** [comment]
具体的错误提示如下。我之前用你3月份左右的版本没有问题，昨天看到你最近更新了，也更新了一下，出现了下面的错误提示，貌似缺少了一个“}”，而且tex系统好像可以自动从错误中恢复。

另外，为了不显示[S.l.]和s.n.，我注释掉了bbx的781、787和788行，不知道和这个有没有关系。

Runaway argument?
{\testCJKfirst {\thefield {title}}\iflistundef {location}{\iffieldequalstr \ETC
.
! File ended while scanning use of \@argdef.
<inserted text> 
                \par 
l.10989 \RequireBibliographyStyle{\blx@bbxfile}
                                               
I suspect you have forgotten a `}', causing me
to read past where you wanted me to stop.
I'll try to recover; but if the error is serious,
you'd better type `E' or `X' now and fix your file.

**Comment by hushidong** [comment]
好的，是git上下的1.0版么？是顺序编码制吧，我看一下，试完了再给你回复。 发自网易邮箱大师 在2017年05月12日 12:21，wayne508 写道： 具体的错误提示如下。我之前用你3月份左右的版本没有问题，昨天看到你最近更新了，也更新了一下，出现了下面的错误提示，貌似缺少了一个“}”，而且tex系统好像可以自动从错误中恢复。 另外，为了不显示[S.l.]和s.n.，我注释掉了bbx的781、787和788行，不知道和这个有没有关系。 Runaway argument? {\testCJKfirst {\thefield {title}}\iflistundef {location}{\iffieldequalstr \ETC . ! File ended while scanning use of @argdef. \par l.10989 \RequireBibliographyStyle{\blx@bbxfile} I suspect you have forgotten a }', causing me to read past where you wanted me to stop. I'll try to recover; but if the error is serious, you'd better typeE' or `X' now and fix your file. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by hushidong** [comment]
我刚试了下，可能是注释的问题，你注视的时候可能多修饰了}符号，781行，788行各有两个}多修饰了。 请教一下，把这些注释了，那标点就用默认的么？还是有需要什么设计？这里我做的时候为了方便考虑，改变了biblatex的标准样式的标点方式，它的方式是根据缺省有特别处理的。我这里如果这样修饰标点可能固定下来了，比如地址后面的冒号。对于这个你有什么看法么？当然固定冒号这种也有好处，就是解析时很根据判断很清楚。 发自网易邮箱大师 在2017年05月12日 12:21，wayne508 写道： 具体的错误提示如下。我之前用你3月份左右的版本没有问题，昨天看到你最近更新了，也更新了一下，出现了下面的错误提示，貌似缺少了一个“}”，而且tex系统好像可以自动从错误中恢复。 另外，为了不显示[S.l.]和s.n.，我注释掉了bbx的781、787和788行，不知道和这个有没有关系。 Runaway argument? {\testCJKfirst {\thefield {title}}\iflistundef {location}{\iffieldequalstr \ETC . ! File ended while scanning use of @argdef. \par l.10989 \RequireBibliographyStyle{\blx@bbxfile} I suspect you have forgotten a }', causing me to read past where you wanted me to stop. I'll try to recover; but if the error is serious, you'd better typeE' or `X' now and fix your file. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by hushidong** [comment]
我刚试了下，可能是注释的问题，你注释的时候可能多注释了}符号，781行，788行各有两个}多注释了。 请教一下，把这些注释了，那标点就用默认的么？还是有需要什么设计？这里我做的时候为了方便考虑，改变了biblatex的标准样式的标点方式，它的方式是根据缺省有特别处理的。我这里如果这样修饰标点可能固定下来了，比如地址后面的冒号。对于这个你有什么看法么？当然固定冒号这种也有好处，就是解析时很根据判断很清楚。 发自网易邮箱大师 在2017年05月12日 12:21，wayne508 写道： 具体的错误提示如下。我之前用你3月份左右的版本没有问题，昨天看到你最近更新了，也更新了一下，出现了下面的错误提示，貌似缺少了一个“}”，而且tex系统好像可以自动从错误中恢复。 另外，为了不显示[S.l.]和s.n.，我注释掉了bbx的781、787和788行，不知道和这个有没有关系。 Runaway argument? {\testCJKfirst {\thefield {title}}\iflistundef {location}{\iffieldequalstr \ETC . ! File ended while scanning use of @argdef. \par l.10989 \RequireBibliographyStyle{\blx@bbxfile} I suspect you have forgotten a }', causing me to read past where you wanted me to stop. I'll try to recover; but if the error is serious, you'd better typeE' or `X' now and fix your file. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by wayne508** [comment]
我在写毕业论文，因为很多bib条目都没有地址和出版商，导致参考文献中就会显示很多的[S.l.]和s.n.，
评审老师指出了这个问题，因此我就把里面的相应几行给注释掉了，具体的标点方式什么的我不太懂，谢谢了！

**Comment by hushidong** [comment]
关于隐藏出版社和出版者，已经有更好的处理方法。即使用gbpub=false。

这个问题已经解决，没有新的情况先关闭了。
