### ISSUE TITLE
\cite 和 \supercite 统一使用 \supercitedelim？

### ISSUE THREAD

**Issue by zepinglee** [hushidong/biblatex-gb7714-2015#95]
```latex
\documentclass{ctexart}
\usepackage[backend=biber,style=gb7714-2015]{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}
  \cite{westfahl:space,aksin,angenendt}\par
  \cite{westfahl:space,angenendt}\par
  \supercite{westfahl:space,angenendt}\par
  \printbibliography
\end{document}
```

<img width="72" alt="Screen Shot 2021-05-30 at 09 03 11" src="https://user-images.githubusercontent.com/12290822/120088696-e1bad280-c125-11eb-99a9-84d243aee245.png">

第二个 `\cite` 的逗号后有空格，而 `\supercite` 的没有。这是因为 `\supercite` 的定义中有 `\let\multicitedelim=\supercitedelim`。这里似乎改为一致更合理？

**Comment by hushidong** [comment]
好的，稍后修正，改成逗号加短空格，使得两边都能兼顾。 hzzmail ***@***.*** 签名由 网易邮箱大师 定制 在2021年05月30日 09:07，Zeping Lee 写道： \documentclass{ctexart}

\usepackage[backend=biber,style=gb7714-2015]{biblatex}

\addbibresource{biblatex-examples.bib}

\begin{document}

  \cite{westfahl:space,aksin,angenendt}\par

  \cite{westfahl:space,angenendt}\par

  \supercite{westfahl:space,angenendt}\par

  \printbibliography

\end{document} 第二个 \cite 的逗号后有空格，而 \supercite 的没有。这是因为 \supercite 的定义中有 \let\multicitedelim=\supercitedelim。这里似乎改为一致更合理？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zepinglee** [comment]
国外的习惯是，一般上标式引用的逗号不加空格，而与正文平排的逗号加空格。比如 Nature。

**Comment by hushidong** [comment]
去掉标点后的空格，跟你那边统一，见 
https://github.com/hushidong/biblatex-gb7714-2015/commit/74967ba71b26ed7ca741a126a14a5fdee3b22eb8
